### ISSUE TITLE
Fix syntax error on line 127 class-enfold-recaptcha-public.php

### ISSUE THREAD

**Issue by lazdins** [KriesiMedia/enfold-library#13]
class-enfold-recaptcha-public.php line 127 should be `"type" 	=> "textarea",`

**Comment by iismaell** [comment]
Thanks. Fixed here: https://github.com/KriesiMedia/enfold-library/commit/1c0970755e369ceb0cadd0f348e789588fa2c4dc#diff-102c06701bf28d5e2adada795c59de84
