### ISSUE TITLE
AviaHtmlHelper display_image method update request for better SVG support

### ISSUE THREAD

**Issue by josueochoa** [KriesiMedia/enfold-library#18]
Hello!

Just a little request to improve svg compatibility when using Image type elements, on AviaHtmlHelper display_image method (/config-templatebuilder/avia-template-builder/php/html-helper.class.php:2355), there's regex match that handles the popup backend preview rendering of the image:

```
if(preg_match('/^.*\.(jpg|jpeg|png|gif)$/i', $img))
```

Can svg be added to regex match, like:
```
if(preg_match('/^.*\.(jpg|jpeg|png|gif|svg)$/i', $img))
```

That way if a svg image is uploaded it will appear in the popup preview, and also allowing for its removal.

![Screen Shot 2020-05-09 at 1 32 13 PM](https://user-images.githubusercontent.com/3257751/81482003-8f94cf80-91f9-11ea-9f2d-8af5939276f1.png)

Thanks!

**Comment by InoPlugs** [comment]
done
