### ISSUE TITLE
Translation of ###91### inti [ doesn't work

### ISSUE THREAD

**Issue by DreiBaer** [KriesiMedia/enfold-library#22]
Hi,

I have the enfold theme installed. And I have created an Email-Formular. The subject of the email to be sent should start with [SEMM]. Therefore, I escaped the characters with ###91### and ###93###. But when I send the mail, the result in my inbox is like this:

--------------------------
###91###SEMM###93### Frage an den Support
--------------------------

What is the problem with my config?

Best Regards
Dreibaer

**Comment by mischa13** [comment]
I tested this with Enfold 5.4 and PHP 8.0.28. I can confirm the error.  The mail subject e.g. ###91## is not de/encoded correctly. 
I recommend you to report this issue to [https://kriesi.at/support/](https://kriesi.at/support/)
I think it is a bug in the theme.
Regards,
M. Spörer

**Comment by mischa13** [comment]
Hi Dreibaer.
Have you tried to urlencode the subject?
e.g. %5BSEMM%5D Frage an den Support
[https://www.urlencoder.org/](https://www.urlencoder.org/)
This actually works on mine installation.
Regards,
M. Spörer

**Comment by InoPlugs** [comment]
@mischa13  @DreiBaer 

Please check new version 1.1.

https://github.com/KriesiMedia/enfold-library/tree/master/integration%20plugins/Enfold/Special%20Character%20Translation

Adds support for ALB contact form.

**Comment by DreiBaer** [comment]
Hi,

I'm sorry, the new version does not fix the problem.

Regards
DreiBaer

**Comment by DreiBaer** [comment]
> Hi Dreibaer. Have you tried to urlencode the subject? e.g. %5BSEMM%5D Frage an den Support https://www.urlencoder.org/ This actually works on mine installation. Regards, M. Spörer

This works, thank you

**Comment by InoPlugs** [comment]
@mischa13 @DreiBaer

Updated to v1.1.1

Now also supports autoresponder subject and message

**Comment by DreiBaer** [comment]
Version 1.1.1 works perfect.
Thanks
