### ISSUE TITLE
Avia Dynamic Content is making the Wordpress slower.

### ISSUE THREAD

**Issue by ip2C** [KriesiMedia/enfold-library#27]
Avia Dynamic Content is making the Wordpress slower.

Your new AddOn is killing my Theme.  So please chjeck the issue for performance. It will be nice to not making the Enfols dslower and slower with every update.

![Bildschirmfoto 2024-07-15 um 11 16 37](https://github.com/user-attachments/assets/e4cd5f54-740f-477a-890f-5ba271f1b1d1)

**Comment by InoPlugs** [comment]
@ip2C 

Goto Theme Options -> Layout Builder -> Limit Number Of WP Default Custom Fields

You can either select "Skip All" or reduce it to 10.

Or disable this feature completly if not needed (Option Custom Layout And Dynamic Content).

**Comment by ip2C** [comment]
Thank you I will try.  Because we have a lot of custom code and acf functions already in our system and today i encountered first issues.
