### ISSUE TITLE
Accordeon Title is changing the Headline to ***

### ISSUE THREAD

**Issue by ip2C** [KriesiMedia/enfold-library#28]
After updating to the new enfold  Three stars ***  are showing up in the accordeons that I used in my custom codes.

I have some custom pages and custom PHP pages.  Now rthe fields are changed and after rendering the page a script is changing the headlines to ***    I could fix this by addibng a span around the custom headlines.

**Comment by InoPlugs** [comment]
@ip2C 

There was a small bug in this element. 

We added the possibility to change title on open or closed state and the aria attributes.

These are the updated files for 6.0.3:

https://github.com/KriesiMedia/enfold-library/tree/master/temp_fixes/Enfold_6_0_2/config-templatebuilder/avia-shortcodes/toggles

Can you please check if these updates fix the problem?

If not, how do you add the *** to the title ?

**Comment by ip2C** [comment]
hmmpf.  Why is enfold / kriesi changing so many already in use elements.  This makes it hard to update older and over all self customed systems like we have a lot.
