### ISSUE TITLE
Sliders all not touchable

### ISSUE THREAD

**Issue by ip2C** [KriesiMedia/enfold-library#29]
Thanks for adding the dynamic content.  But...    I think this is just for developpers usefull and they know how to handle with acf and metaboxes... 

What we really need is that sliders are swipeready. All sliders should be moving on touchstart and on swipe effects of mouse and fingers?    Please could you focus on that on the next update?

**Comment by ip2C** [comment]
for the horizontal gallery it takes me a while:  https://spemot.24-u.de/wp-content/themes/enfold/config-templatebuilder/avia-shortcodes/gallery_horizontal/gallery_horizontal.js

**Comment by InoPlugs** [comment]
@ip2C 

Thanks.

We added support for swipe already - could be we missed some elements. But I will recheck and check for mouse.

See enfold\js\shortcodes.js line 1285:

$.fn.avia_swipe_trigger

**Comment by ip2C** [comment]
Hi,    can you show me where I can use swipeactions because with a newest installation   on my Server:  https://enfold-basic.24-u.de/about/    I tested the fullscreenslider and it is not working here with touchstart or swipe effects.

**Comment by ip2C** [comment]
I think we on a good state .  with my new version of enfold page (keeping it small and slim) I think the most sliders are swipeable  of course they moving differnet like the swipeslider / flexslider and all the others well known sliders. But this is ok.  So I think we can clode this here.    MAybe you will take look on my addon I send   https://spemot.24-u.de/wp-content/themes/enfold/config-templatebuilder/avia-shortcodes/gallery_horizontal/gallery_horizontal.js
