### ISSUE TITLE
Making Enfold better and better:

### ISSUE THREAD

**Issue by ip2C** [KriesiMedia/enfold-library#32]
CSS errors :

These all are Mozilla  Warnings in the Enfold base CSS 

Fehler beim Verarbeiten des Wertes für 'min-height'.  Deklaration ignoriert. [content.css:26:238](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für 'min-height'.  Deklaration ignoriert. [content.css:27:238](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für 'letter-spacing'.  Deklaration ignoriert. [content.css:41:442](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für 'transition'.  Deklaration ignoriert. [content.css:41:677](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für 'letter-spacing'.  Deklaration ignoriert. [content.css:42:102](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für 'margin'.  Deklaration ignoriert. [content.css:45:2354](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für 'margin'.  Deklaration ignoriert. [content.css:66:1026](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für 'margin'.  Deklaration ignoriert. [content.css:72:2437](moz-extension://bb3654c1-3466-4e06-a8a8-4bb8be8ed478/build/content.css)
Fehler beim Verarbeiten des Wertes für '-webkit-text-size-adjust'.  Deklaration ignoriert. [base.min.css:1:981](https://lp.schlossfestspiele.de/wp-content/themes/enfold/css/base.min.css?ver=6.0.3)
Unbekannte Eigenschaft 'speak'.  Deklaration ignoriert. [base.min.css:1:5386](https://lp.schlossfestspiele.de/wp-content/themes/enfold/css/base.min.css?ver=6.0.3)

**Comment by InoPlugs** [comment]
@ip2C 

Thanks.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

I added text-size-adjust for 6.0.5


https://css-tricks.com/almanac/properties/s/speak/
https://caniuse.com/?search=speak

Not supported by many browsers - but we keep it in case support will come.
