### ISSUE TITLE
Menu tem Accessiblity Issues

### ISSUE THREAD

**Issue by ip2C** [KriesiMedia/enfold-library#33]
Einige untergeordnete ARIA-Rollen müssen in bestimmten übergeordneten Rollen enthalten sein, damit sie die beabsichtigten Hilfsfunktionen erfüllen können. [Weitere Informationen zu ARIA-Rollen und erforderlichen übergeordneten Elementen.]

Fehlerhafte Elemente
Datenschutz

```

<li id="menu-item-2229" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2229" role="menuitem">

```

Please add role menu  to the ul element for menus

**Comment by vatoyiit** [comment]
@ip2C 
By default, the ul tag in the navigation has Menu as the Role attribute:
![Screenshot 2024-09-17 at 14 56 07](https://github.com/user-attachments/assets/026fba91-e6fe-4693-9fa8-0adac2619646)

If you don't have this attribute on your installation, please make sure:
- you're using Enfold 6.0.4
- the active theme is the Enfold parent theme
- all plugins are deactivated 

If that doesn't work, please start a thread on our support forum ( https://kriesi.at/support ) so we can investigate it.

**Comment by ip2C** [comment]
Ah nice.  I have a new Footermenu added and this is not an avia-menu.   So this was set as bad accessibility.  I added a Javascript for this

**Comment by vatoyiit** [comment]
Glad you figured out the issue. This attribute is available on the Enfold's Main, Secondary, and Footer menus.
