### ISSUE TITLE
Tiny MCE - is loading sometimes 1 and then the other version.

### ISSUE THREAD

**Issue by ip2C** [KriesiMedia/enfold-library#34]
In all my Enfold projects my clients are complaining that they often can not use the standard Enfold Tiny MCE :  

![Bildschirmfoto 2024-10-08 um 10 10 20](https://github.com/user-attachments/assets/86179ab5-5487-44a3-8af6-e62419c2d6aa)

It often loads this version: 
![Bildschirmfoto 2024-10-08 um 10 11 44](https://github.com/user-attachments/assets/2f399aa3-aa20-48e7-a5b4-e35b48ca3bf3)

Any help please!

**Comment by InoPlugs** [comment]
@ip2C 

This is a problem with WP, tinyMCE and browser cache.

Clear browser cache and reload the page (or open in a new tab) solves it.

No idea why this happens.
